# Generated by Django 3.2.7 on 2022-03-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parsing", "0002_marketplace_price_per_meter"),
        ("parsing", "0003_auto_20220321_0110"),
    ]

    operations = []
