"""
Django settings for my_parser project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from telegram import Bot

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("ENV_SECRET_KEY")
PAGES_TO_PARSE = 100
REDEMPTION_VALUE = 50_000
OLD_MIN_VALUE = 47_000
NEW_MAX_VALUE = 50_000
BOT_TOKEN = os.environ.get("BOT_TOKEN")
CHAT_ID = os.environ.get("CHAT_ID")
AVITO_HEADERS = {
    # "Transfer-Encoding": "chunked",
    "Connection": "keep-alive",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "cache-control": "max-age=0",
    "Accept-Language": "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
    "cookie": 'buyer_laas_location=656901; buyer_index_tooltip=1; buyer_local_priority_v2=0; _ym_d=1625261071; _ym_uid=1625261071324091915; _fbp=fb.1.1625261072013.742585316; seedr_cid=81bc726c-c807-40b9-9778-a527db34f216; __utmz=99926606.1625261086.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); uxs_uid=efec1920-db7b-11eb-972a-51d627cb95ad; auth=1; __utma=99926606.1698236505.1625261072.1625261086.1625263342.2; _gcl_au=1.1.771077711.1633189056; cto_bundle=w76Fh19tNjJEUDlZMkQlMkJNbXRMUHdDJTJCaGRzcHo2QzNhWEYxSkdwVVA1T1dXbzlqQTVKcjdFemFWdXdvZHZLZUxKTXpzMU8wMWxvWnZsTGYlMkJ5SlVYZmdVcmc4dkJoSFlIbDY0ZkNMciUyQmJmeWtwc0N4UGtzUlhGQzB5THFUTU9JM1ZvVyUyRmg; u=2oxr74wm.cy8nte.1ue4m0dtgmv00; tmr_lvid=2345626540db8df88c47acbca3cbe6a0; tmr_lvidTS=1635149992594; __gads=ID=197ca3a6f7abe2f8:T=1625263383:S=ALNI_MZkrPZ9fvVKzExZZ4xD9Uxun5bw9A; showedStoryIds=76-75-74-71-69-68-66-63-61-50-49; lastViewingTime=1636656004417; sessid=d9cea5fc2cb62e27268b13a3b582f30e.1637319609; _gcl_aw=GCL.1637578808.CjwKCAiAnO2MBhApEiwA8q0HYey0H71J4MOBZUoytA_lbaPOZ9P9aVu7U9fbIr2VZRPQjaF6roN_PxoCqUsQAvD_BwE; _gid=GA1.2.641954171.1637578808; _gac_UA-2546784-1=1.1637578808.CjwKCAiAnO2MBhApEiwA8q0HYey0H71J4MOBZUoytA_lbaPOZ9P9aVu7U9fbIr2VZRPQjaF6roN_PxoCqUsQAvD_BwE; _ym_isad=2; f=5.9fd3735f16182a2836b4dd61b04726f147e1eada7172e06c47e1eada7172e06c47e1eada7172e06c47e1eada7172e06cb59320d6eb6303c1b59320d6eb6303c1b59320d6eb6303c147e1eada7172e06c8a38e2c5b3e08b898a38e2c5b3e08b890df103df0c26013a0df103df0c26013a2ebf3cb6fd35a0ac0df103df0c26013a8b1472fe2f9ba6b9fb1d403eb594feea68e2978c700f15b6bf11f980bc2bc377f2c082410b22639b04dbcad294c152cb0df103df0c26013aba0ac8037e2b74f9268a7bf63aa148d20df103df0c26013a8b1472fe2f9ba6b97b0d53c7afc06d0b71e7cb57bbcb8e0f03c77801b122405c03c77801b122405c7b0d53c7afc06d0b2ebf3cb6fd35a0ac8b1472fe2f9ba6b9b892c6c84ad16848a9b4102d42ade879dcb5a55b9498f642b81f1c77c4dcf4df4fb29506e8757e3c7b35ff6e25b8e341a7f6805d696a2537fd6c23efc8659514df6217fad9a168c21e769b15ee417e9591e52da22a560f550df103df0c26013a0df103df0c26013aaaa2b79c1ae925952ed2c6ebf476365b6a10d95aee71bb8b3de19da9ed218fe2c772035eab81f5e110e95b305e77352aa1a4201a28a6ec9b059080ed9becc4cd; ft="kcAyInfpaYKroXwd1gmT+f/l29KLV9nzOu4ZU0EB7+moUcEscraD14C2mYqzqz7FdyXjW65kltdG1HMflJtK1xfVUidW5kf8qNpTaiFbL0RYg9P4C96CFX8fBpvBd2k1sp5WHaDn+tDVZK5/QNKNz2rsKN3lyNG0gsHlXEsc0WNZI9IDsz9f3oJujBgU2Qbz"; tmr_detect=0%7C1637578810942; tmr_reqNum=39; st=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidko0TkJ5SlU2TElJTGRDY3VNTkdBZm5PRWwySzdtS01KZXBFMDh1VUFISkV6Z3lNMTNDQWQ2RnQ0bENpWUNQQXNsbW5rd0RmNVV6YklZendveE8zdFNzR1VRQmtNbisxUTMrbG1CUyszTDZuWU83TzBGYWVZdldReE4xS0hlSG1zM1dBd0Z5SzFRWjIybTYvMDlKK1hOV2xGVzJWTUNyenJ2Q1g2dXFLdEI2ZFQ3Y1JtU1o1SXhJZ0wwYU9pNHh6WExJVjhWeUJFTXFVMDRENDhTMHVWUkJGV3NqdVBlNmU3UUg3OVZnWmVvSXFpNFRVbXM3WWNoVytrL1B1TjdOeXlzRkFYTVh3UU1DdjYzTkJNVTlQL2MyS25hMHJ3S09sbUg5eXhhNi9IalMyTWdMeFFvYThIMlpsT2lURFRWbVNuallsZjJ2dlRWREU0NHJ0MllpcFBxNWZEdTVsV1BaTng3UEVHT3REQWhRWGNNd2YyNllIMEZ2bXg4N2U0d1RwUDFzMFoxWUt4U0hKM2c5L1lwMmgrV2dia0U4QmFmMjUrWGJuUHNNSmpzZTZ1a3VSNC9vUVozY0lKSDdTSVpFWVFpRUJ2QmQrTXE3YzNmN05QR3ROaGRQN3JoMERMY0FWQkpEOGFhMFdiemxuaE5yU2lNaGQ3Vmg3NUE4SVVWRUdRRWhTempyUU5NSnZpamNvZ2lVbmxRVXE1Z2hBZUs4QjlzRm1KYjFTYVd3WFJ4YzBSTzZ4SmpURjZyOTN6alV5L2RocGVZS0U0Q3NZUWpJWm5FUjhRNi9nTDdsNHJEamNub2x6RkoxNUpqVmR6MUpFcm5jbDVNdHFaTXFhZ2l1cllKdWo4YzAvZmFGcG9UUm5wcmxDeWw5NERHaWRYa3c5Ymhkdis2N2RJaDB2SFhiTVZleng1MnJUa3RhMlJPYThGbHlhZXFRV0VaOU9RcjdmTnc3Tkt1UDBwellJcXBWeDdaY1YwaXNDdWFVRHJvQUJRN1Y4NFB0eWdaTDA0MFZ5N29WRUVONys4VE1UY2ZoT2RyWVRva3JmRytua1dxWXlBU1JVNnAyUWRicUZKR000bzNLcGVpd2pQZUcwSzJkYjI0R3FNMS92b0FsSWxBZWllV2lqOTBPVXJiQWhYZmlzSkI0MU83TmgzRFR0VnJnazRBcVczTWFLWk9mS3RNV3lIQ0Rmc1FTeUlmSnFzSTZoQitsdE93VUpLOU9PdlY5M2MvRzM3c1ZFU2d0NjZaQmNkNjREeVBUMXJrVTdISmJ2S3BtNDBSNHk2MU5oV2drUnNzdWk0WDc2dktkUFJVM20vZjJ1Y2NQOW5Dem9pR25qMkRhQUlkdCtxaXdlQVk3T2ZhYVVwU0ZuazY4eXRTV2g0dFBsLzdSWHZmZXdFelVrbi9SdGtzYnhGZk15YSt0ZGVwRkg0NEU2RXBPcXdBd0lMMDZDdkVoVDNxcDgvV3lWWmlpbnI1OTNLb21QRHNldEo3dkVUcXlWSG9JaTY2aXhsUFhnQ3Y5UHVyRlVPMnZBVlpFNDdqMk9RdXhWc3puSjZoR0Iwc0tCRGRyUkp2eUF6OHIzcEVQVFhScjBJVUV6bkM0OEtWRXplWkJBaG1MSEdpbkJsVlhMK1NDWk1vWDVMN014Y0E9PSIsImlhdCI6MTYzNzU3ODgzNiwiZXhwIjoxNjM4Nzg4NDM2fQ.lagT4xNAO4fbHjPxqFYb5q5hQXJYSMWtQk27oZC6Lyo; SEARCH_HISTORY_IDS=1%2C3%2C4%2C; buyer_location_id=656901; luri=tver; buyer_popup_location=656901; sx=H4sIAAAAAAAC%2F1zQS47qMBBA0b14zMCfcpWL3fhXDjwIIYYoBGXvTz2g1d0bOLq6b2VqjkC6EBSRwCzVuBB1jboAe43q%2BFaLOqq5p2l6lttcTPPorsE%2Fz5PA%2FV57T2jVQVV1NOgI0ZPF%2FaAQEXMhFEb2CMiVUnVcyOucqfC3DGEx3q2DHtZ7xzrmLZ2XC5weq15n80sGa%2FaDYg4BmXQsMdjgUipe0AYPpYCzBB%2B5nxr2WAXP%2BjWDkN8ur6xjc%2FJsNT1%2BymzCV3O2LnlxbLhgJBIyQTK4ICZyMmQ%2FcpugjbDcXqP%2Fx1cOy2Vo42bc0JfrRNufG3bf%2FwcAAP%2F%2FBBoRMWkBAAA%3D; abp=0; _ga_9E363E7BES=GS1.1.1637582785.96.1.1637582785.60; _ga=GA1.1.1698236505.1625261072; v=1637587043',

}
# 'Server': 'QRATOR',
# 'Date': 'Thu, 04 Nov 2021 13:09:28 GMT',
# 'Content-Type': 'text/html; charset=utf-8',
# 'Keep-Alive': 'timeout=15',
# 'set-cookie': 'u=2oz9y5ww.cy8nte.3s4svfu2b88',
# "Accept": "*/*",

bot = Bot(token=BOT_TOKEN)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "parsing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_parser.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_parser.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
