"""
Django settings for my_parser project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from telegram import Bot

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("ENV_SECRET_KEY")
PAGES_TO_PARSE = 100
REDEMPTION_VALUE = 60_000
OLD_MIN_VALUE = 57_000
NEW_MAX_VALUE = 60_000
BOT_TOKEN = os.environ.get("BOT_TOKEN")
CHAT_ID = os.environ.get("CHAT_ID")
AVITO_HEADERS = {
    # "Connection": "keep-alive",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "accept-encoding": "gzip, deflate, br",
    "cache-control": "max-age=0",
    "Accept-Language": "ru,en;q=0.9",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
    # "cookie": 'buyer_laas_location=656901; buyer_index_tooltip=1; buyer_local_priority_v2=0; _ym_d=1625261071; _ym_uid=1625261071324091915; _fbp=fb.1.1625261072013.742585316; seedr_cid=81bc726c-c807-40b9-9778-a527db34f216; __utmz=99926606.1625261086.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); uxs_uid=efec1920-db7b-11eb-972a-51d627cb95ad; auth=1; __utma=99926606.1698236505.1625261072.1625261086.1625263342.2; _gcl_au=1.1.771077711.1633189056; cto_bundle=w76Fh19tNjJEUDlZMkQlMkJNbXRMUHdDJTJCaGRzcHo2QzNhWEYxSkdwVVA1T1dXbzlqQTVKcjdFemFWdXdvZHZLZUxKTXpzMU8wMWxvWnZsTGYlMkJ5SlVYZmdVcmc4dkJoSFlIbDY0ZkNMciUyQmJmeWtwc0N4UGtzUlhGQzB5THFUTU9JM1ZvVyUyRmg; u=2oxr74wm.cy8nte.1ue4m0dtgmv00; tmr_lvid=2345626540db8df88c47acbca3cbe6a0; tmr_lvidTS=1635149992594; __gads=ID=197ca3a6f7abe2f8:T=1625263383:S=ALNI_MZkrPZ9fvVKzExZZ4xD9Uxun5bw9A; showedStoryIds=76-75-74-71-69-68-66-63-61-50-49; lastViewingTime=1636656004417; sessid=d9cea5fc2cb62e27268b13a3b582f30e.1637319609; _gid=GA1.2.641954171.1637578808; buyer_location_id=656901; SEARCH_HISTORY_IDS=1%2C3%2C4%2C; _ym_isad=2; tmr_detect=0%7C1637741964013; tmr_reqNum=48; adjust_links=adgroup%3Dweb_google_buyers_c2c_general_all_search_01042020_regother_generic_perf%26campaign%3Dgoogle%26creative%3D%252B%25D0%25B0%25D0%25B2%25D0%25B8%25D1%2582%25D0%25BE; buyer_popup_location=0; luri=tver; f=5.9fd3735f16182a2836b4dd61b04726f147e1eada7172e06c47e1eada7172e06c47e1eada7172e06c47e1eada7172e06cb59320d6eb6303c1b59320d6eb6303c1b59320d6eb6303c147e1eada7172e06c8a38e2c5b3e08b898a38e2c5b3e08b890df103df0c26013a0df103df0c26013a2ebf3cb6fd35a0ac0df103df0c26013a8b1472fe2f9ba6b9fb1d403eb594feea68e2978c700f15b6bf11f980bc2bc377f2c082410b22639b04dbcad294c152cb0df103df0c26013aba0ac8037e2b74f9268a7bf63aa148d20df103df0c26013a8b1472fe2f9ba6b97b0d53c7afc06d0b71e7cb57bbcb8e0f03c77801b122405c03c77801b122405c7b0d53c7afc06d0b2ebf3cb6fd35a0ac8b1472fe2f9ba6b9b892c6c84ad16848a9b4102d42ade879dcb5a55b9498f642b81f1c77c4dcf4df4fb29506e8757e3c7b35ff6e25b8e341a7f6805d696a2537fd6c23efc8659514df6217fad9a168c21e769b15ee417e9591e52da22a560f550df103df0c26013a0df103df0c26013aaaa2b79c1ae925951330ca096ca7f42f8785126b3b0851be3de19da9ed218fe2c772035eab81f5e110e95b305e77352aa1a4201a28a6ec9b059080ed9becc4cd; ft="f4g/bDP1AIK5VVuTvNi50xRAYkRW6jGmE/1+LpvSI7E0EV9BDUXFR5m5qDMBPm/ezDYrRNVImeCpG4k9jWwNjTuA2JkVnKlS5kvB8FLVzc784xwNAD2apEeDVaIgZnE1Ze8/4RURZYvIARpgEreYdeRgVcxQ0BawgBDxMrcvOTeWfhBiqq7iYDdAQCRCnE37"; st=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidko0TkJ5SlU2TElJTGRDY3VNTkdBZm5PRWwySzdtS01KZXBFMDh1VUFISkV6Z3lNMTNDQWQ2RnQ0bENpWUNQQXNsbW5rd0RmNVV6YklZendveE8zdFNzR1VRQmtNbisxUTMrbG1CUyszTDZuWU83TzBGYWVZdldReE4xS0hlSG1zM1dBd0Z5SzFRWjIybTYvMDlKK1hOV2xGVzJWTUNyenJ2Q1g2dXFLdEI2ZFQ3Y1JtU1o1SXhJZ0wwYU9pNHh6WExJVjhWeUJFTXFVMDRENDhTMHVWUkJGV3NqdVBlNmU3UUg3OVZnWmVvSXFpNFRVbXM3WWNoVytrL1B1TjdOeXlzRkFYTVh3UU1DdjYzTkJNVTlQL2MyS25hMHJ3S09sbUg5eXhhNi9IalMyTWdMeFFvYThIMlpsT2lURFRWbVNuallsZjJ2dlRWREU0NHJ0MllpcFBxNWZEdTVsV1BaTng3UEVHT3REQWhRWGNNd2YyNllIMEZ2bXg4N2U0d1RwUDFzMFoxWUt4U0hKM2c5L1lwMmgrV2dia0U4QmFmMjUrWGJuUHNNSmpzZTZ1a3VSNC9vUVozY0lKSDdTSVpFWTZITzArVkd5SlM0QWYvR2RKbnJHeWNRKzQ1Vmt5THRKQ1MvdzRXWGo5QWk2RXpRS1NBT1BJUmU5ckwzWU5xcFJabEVyc0hiSzAzcTVtbitZZzhDNWhXQ0FyMXhpaDE3SVlHQjFVY3N6UTd4a3JjRWhoWGxBL3p5RUJyWVViSE55TG4wRjlWbWFCem5VQlI5ZnNRdk9HVHBwWG9obnhUTmZJbFhkVG9Vczhtb0hPTTRTVGF0c2Z6T0NzVThYSlh6d3pyNUc0NHBaZVNPQjVidHcxNHNOQ0w0M3poZkJPUHJMejE0bEI2cVpXc2NBOGxSWm9sK0VaYXBMMTdGbGNmUUdXbnBzcjZ1elZZc01BWGlWd1ZQanV5MkxFZ2JBUUNoN2ZzMDVXS0tLSExPcFprMlpGZ29TQ2hWVXhPUENDU1k4aC9YMzlxaDBEMmo0WTJzU3JuaVU5ZElIZWxjditBcEpWbWhRNWVXemVQenltMHlKV29neFNLNXZBK0pRV3pLTy84dUQvZy90emFYYVludFB4M203dFF5UzJMMlpKQitaN3VtMTQ5RFVTaE85MmMvRzFmWTFnVzZTWjZ3dTBOclE2RnhTL25wR1ZzZStEMitRbFo1dmxEdTFGZHN6Z3BpSHhZaExTeWhIbUhIRVdudzNaVzlNSGg5VFNTY1IzOWpiME51aG1GenRMZHJXYXJ3Ulp0K1IrZFNFZFVXMHlMMUFXUFArZ2hrNngwTnIzSG9EbFJMdHRzSzBwcEZlakJFbmFjNmxSMlF3SHNKdW5sUE9YRXk0ZWU0Zjhid0d3WjNEdGVkSzFIQVY3cGl2cHM4MmRZYkR1dnRYbkZ2ZmNuY282VjUxQ3BMRFFJN2ZndHRHSjU0emlDajJpcVczTmdEU05nNWJvK3FseVVBUEg4dC9KRWxyNm1rZlByUjg3VTFvRVM1WlI4VWxKaXpjdVV2QzRsUk9aR1Foc1hTNmM2eTVXUmN2SlZxNVYybzR0RlNzOC9pOWs1b2g4N095czNFV3R0T0xHQWkzb3VLb0FlajVyS1hrcnc9PSIsImlhdCI6MTYzNzc0MTc3MywiZXhwIjoxNjM4OTUxMzczfQ.JhnVuaROuCYjH9BlUHuRM0x6vyyY3H8PH4CcZy_Ls9U; v=1637767399; dfp_group=89; isLegalPerson=1; _gcl_aw=GCL.1637767397.CjwKCAiA4veMBhAMEiwAU4XRr9EkXpf2LJo-ekXvGZr1biNP1o9nrHzN4WjmKiPlxLapvmkNpRdoQBoCYAcQAvD_BwE; _ym_visorc=b; _gac_UA-2546784-1=1.1637767398.CjwKCAiA4veMBhAMEiwAU4XRr9EkXpf2LJo-ekXvGZr1biNP1o9nrHzN4WjmKiPlxLapvmkNpRdoQBoCYAcQAvD_BwE; sx=H4sIAAAAAAAC%2F1TOyXHrMAwA0F549oEgQAB0N1ylWPIua0lGvf%2F5B2fiBt68HwNkuVUoTTLYrLEwBRcSQgqSbQNz%2FDGzOZqIAzLNcOJhekkKr2%2B9PnJYv9KTot3MwVRzBEZRJCLdDwadI2zJJ0zNMST0oTa24BQxNQ5v2Z26O%2FgiMZ577S%2FbZBeGi90WODV3t58y%2FpeZrZMKsVTbag1a2ElBLaLee6j2La9wvpMfrdX1SztyycFlSGR968qzv%2F6RPaqF%2FWAEi%2FjGLQs7FIjCoiCuFZ8JWH%2FlOm51lkcZ1%2BWU0%2Fgqw62dx2kYY%2Byopw9ZQtgPJgRVDmJjieoUUyq%2BsVNPpRA6obd81q6bw6O%2FXa7rcMtT7TU%2Bh%2Fhy%2FfeUaPorA3ncDyaqJ1%2FEBxuLTUVVfCwB1Aq16Lx7y1t9DQvDvVvmYcTuyemZH3i5Rs6nHOePc8Cw7%2F8CAAD%2F%2F%2FcHQJgdAgAA; _ga_9E363E7BES=GS1.1.1637767396.106.1.1637767537.60; abp=0; _ga=GA1.2.1698236505.1625261072; _dc_gtm_UA-2546784-1=1; buyer_from_page=catalog',
}

bot = Bot(token=BOT_TOKEN)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "parsing",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_parser.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_parser.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
